import {
  Rocket01Icon,
  Diamond01Icon,
  SkullIcon,
  Search01Icon,
  Message01Icon,
  FireIcon,
  ZapIcon,
  Coins01Icon,
  Briefcase01Icon,
  GameController03Icon,
  HealthIcon,
  UserGroupIcon,
  Globe02Icon,
  Clock01Icon,
  ChartBreakoutSquareIcon,
  StarIcon,
  Shield01Icon,
  Megaphone01Icon,
  Camera01Icon,
  Bug01Icon,
  Brain02Icon,
  Medal06Icon,
} from "hugeicons-react";
import { MicroscopeIcon } from "lucide-react";

export type AchievementTier = "COMMON" | "RARE" | "LEGENDARY" | "MYTHIC";

export const ACHIEVEMENTS_LIST = [
  // --- 1. EXISTING (CORE) ---
  {
    id: "first_blood",
    title: "First Blood",
    description: "Performed your first app analysis.",
    xp: 50,
    tier: "COMMON",
    icon: Rocket01Icon,
  },
  {
    id: "streak_master",
    title: "Consistency is Key",
    description: "Maintained a 7-day usage streak.",
    xp: 150,
    tier: "RARE",
    icon: FireIcon,
  },
  {
    id: "gold_miner",
    title: "Gold Miner",
    description: "Found an opportunity with Score > 85.",
    xp: 300,
    tier: "LEGENDARY",
    icon: Diamond01Icon,
  },
  {
    id: "necromancer",
    title: "Necromancer",
    description: "Analyzed an app abandoned for > 3 years.",
    xp: 200,
    tier: "RARE",
    icon: SkullIcon,
  },
  {
    id: "data_hoarder",
    title: "Data Hoarder",
    description: "Reached 100 total analyses.",
    xp: 500,
    tier: "MYTHIC",
    icon: Search01Icon,
  },
  {
    id: "ai_whisperer",
    title: "AI Whisperer",
    description: "Sent 50 messages to KiritaAI chatbot.",
    xp: 100,
    tier: "COMMON",
    icon: Message01Icon,
  },

  // --- 2. VOLUME (PROGRESSION) ---
  {
    id: "research_rookie",
    title: "Market Tourist",
    description: "Analyzed your first 10 apps.",
    xp: 100,
    tier: "COMMON",
    icon: Search01Icon,
  },
  {
    id: "research_expert",
    title: "Pattern Hunter",
    description: "Analyzed 50 apps.",
    xp: 250,
    tier: "RARE",
    icon: ChartBreakoutSquareIcon,
  },
  {
    id: "prompt_engineer",
    title: "Prompt Engineer",
    description: "Sent 200 messages to KiritaAI. You love talking!",
    xp: 300,
    tier: "RARE",
    icon: Brain02Icon,
  },

  // --- 3. QUALITY HUNTERS (SCORES) ---
  {
    id: "sniper",
    title: "Sniper",
    description: "Found 5 opportunities with Score > 80.",
    xp: 200,
    tier: "RARE",
    icon: Medal06Icon,
  },
  {
    id: "elite_hunter",
    title: "Elite Hunter",
    description: "Found 3 opportunities with Score > 90.",
    xp: 400,
    tier: "LEGENDARY",
    icon: StarIcon,
  },
  {
    id: "unicorn_spotter",
    title: "The Unicorn",
    description: "Found the perfect gap: An app with Score 98+.",
    xp: 1000,
    tier: "MYTHIC",
    icon: ZapIcon,
  },

  // --- 4. CATEGORIES (EXPLORATION) ---
  {
    id: "wolf_of_wall_street",
    title: "Wolf of Wall St.",
    description: "Analyzed 3 apps in Finance category.",
    xp: 150,
    tier: "RARE",
    icon: Coins01Icon,
  },
  {
    id: "productivity_guru",
    title: "Efficiency Guru",
    description: "Analyzed 5 apps in Productivity category.",
    xp: 150,
    tier: "RARE",
    icon: Briefcase01Icon,
  },
  {
    id: "gamer",
    title: "Player One",
    description: "Analyzed 5 Games.",
    xp: 100,
    tier: "COMMON",
    icon: GameController03Icon,
  },
  {
    id: "biohacker",
    title: "Biohacker",
    description: "Analyzed 3 Health & Fitness apps.",
    xp: 150,
    tier: "RARE",
    icon: HealthIcon,
  },
  {
    id: "socialite",
    title: "The Socialite",
    description: "Analyzed 3 Social Networking apps.",
    xp: 150,
    tier: "COMMON",
    icon: Megaphone01Icon,
  },
  {
    id: "globetrotter",
    title: "Globetrotter",
    description: "Analyzed 3 Travel & Local apps.",
    xp: 150,
    tier: "COMMON",
    icon: Globe02Icon,
  },

  // --- 5. TECHNICAL FINDS (SPECIFIC SCENARIOS) ---
  {
    id: "giant_slayer",
    title: "Giant Slayer",
    description: "Found an app with >10M downloads but <3.0 rating. (Huge gap!)",
    xp: 500,
    tier: "LEGENDARY",
    icon: UserGroupIcon,
  },
  {
    id: "niche_finder",
    title: "Niche Finder",
    description: "Analyzed an app with less than 10k downloads.",
    xp: 200,
    tier: "RARE",
    icon: MicroscopeIcon,
  },
  {
    id: "fresh_blood",
    title: "Fresh Blood",
    description: "Analyzed an app released less than 30 days ago.",
    xp: 200,
    tier: "RARE",
    icon: Clock01Icon,
  },
  {
    id: "bug_hunter",
    title: "Bug Hunter",
    description: "Analyzed an app where 'Crash' is a top pain point.",
    xp: 150,
    tier: "COMMON",
    icon: Bug01Icon,
  },
  {
    id: "privacy_advocate",
    title: "Privacy Advocate",
    description: "Analyzed an app with very few permissions required.",
    xp: 150,
    tier: "COMMON",
    icon: Shield01Icon,
  },
  {
    id: "visual_critic",
    title: "Visual Critic",
    description: "Analyzed an app and viewed its screenshots via modal.",
    xp: 50,
    tier: "COMMON",
    icon: Camera01Icon,
  },
] as const;

export const QUEST_SET_BONUSES = {
  DAILY: {
    title: "Daily Set Completed",
    description: "You finished all daily tasks!",
    xp: 200,
    icon: "FireIcon",
  },
  WEEKLY: {
    title: "Weekly Set Completed",
    description: "Outstanding performance this week!",
    xp: 500,
    icon: "Trophy01Icon",
  },
};
